<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitedd019bb43391f7769ea06efc5d44657
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitedd019bb43391f7769ea06efc5d44657', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitedd019bb43391f7769ea06efc5d44657', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        \Composer\Autoload\ComposerStaticInitedd019bb43391f7769ea06efc5d44657::getInitializer($loader)();

        $loader->register(true);

        return $loader;
    }
}
